version: '3.8'

services:
  regression:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
    command: /bin/sh -c "ls -la && ${TEST_COMMAND}"
    working_dir: /usr/workspace
    env_file:
      - .env